In [1]:
# reading data
import pandas
import numpy as np
features = pandas.read_csv('train_bnp.csv',index_col='ID')
features.head()

,target,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v122,v123,v124,v125,v126,v127,v128,v129,v130,v131
ID,,,,,,,,,,,,,,,,,,,,,
3,1,1.335739,8.727474,C,3.921026,7.915266,2.599278,3.176895,0.012941,9.999999,...,8.000000,1.989780,0.035754,AU,1.804126,3.113719,2.024285,0,0.636365,2.857144
4,1,NaN,NaN,C,NaN,9.191265,NaN,NaN,2.301630,NaN,...,NaN,NaN,0.598896,AF,NaN,NaN,1.957825,0,NaN,NaN
5,1,0.943877,5.310079,C,4.410969,5.326159,3.979592,3.928571,0.019645,12.666667,...,9.333333,2.477596,0.013452,AE,1.773709,3.922193,1.120468,2,0.883118,1.176472
6,1,0.797415,8.304757,C,4.225930,11.627438,2.097700,1.987549,0.171947,8.965516,...,7.018256,1.812795,0.002267,CJ,1.415230,2.954381,1.990847,1,1.677108,1.034483
8,1,NaN,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Z,NaN,NaN,NaN,0,NaN,NaN

In [2]:
features['v91'].value_counts()

A    27079
G    24545
C    23157
B    22683
F    13418
E     3206
D      230
Name: v91, dtype: int64

In [3]:
#found NaN in data
a=features.count()
b=a[a>65000]

In [4]:
#features with NaN
features=features[b.index]
features.head()

,target,v3,v5,v8,v10,v12,v14,v21,v22,v24,...,v108,v109,v110,v112,v114,v117,v124,v125,v128,v129
ID,,,,,,,,,,,,,,,,,,,,,
3,1,C,7.915266,0.012941,0.503281,6.085711,11.636387,7.730923,XDX,C,...,2.382692,3.930922,B,O,15.634907,6.592012,0.035754,AU,2.024285,0
4,1,C,9.191265,2.301630,1.312910,6.507647,11.636386,6.763110,GUV,C,...,1.825361,4.247858,A,U,10.308044,10.595357,0.598896,AF,1.957825,0
5,1,C,5.326159,0.019645,0.765864,6.384670,9.603542,5.245035,FQ,E,...,1.375753,1.184211,B,S,11.205561,3.478911,0.013452,AE,1.120468,2
6,1,C,11.627438,0.171947,6.542669,9.646653,14.094723,7.517125,ACUE,D,...,2.230754,1.990131,B,J,13.777666,4.949609,0.002267,CJ,1.990847,1
8,1,C,NaN,NaN,1.050328,6.320087,10.991098,6.414567,HIT,E,...,NaN,NaN,A,T,14.097099,NaN,NaN,Z,NaN,0

In [5]:
length=len(features)
k=features.dtypes
float_feat=k[k=='float']
int_feat=k[k=='int64']
# target variable
y=np.array(features['target'])

In [6]:
float_feat=float_feat.append(int_feat)
float_feat=float_feat[float_feat.index!='target']

In [7]:
features=features[float_feat.index]
features

,v5,v8,v10,v12,v14,v21,v25,v34,v36,v40,...,v108,v109,v114,v117,v124,v128,v38,v62,v72,v129
ID,,,,,,,,,,,,,,,,,,,,,
3,7.915266,0.012941,0.503281,6.085711,11.636387,7.730923,0.139412,7.270147,11.326592,7.711453,...,2.382692,3.930922,15.634907,6.592012,3.575369e-02,2.024285,0,1,1,0
4,9.191265,2.301630,1.312910,6.507647,11.636386,6.763110,3.056144,3.615077,14.579479,14.305766,...,1.825361,4.247858,10.308044,10.595357,5.988956e-01,1.957825,0,2,2,0
5,5.326159,0.019645,0.765864,6.384670,9.603542,5.245035,0.113997,4.043864,12.730517,13.077201,...,1.375753,1.184211,11.205561,3.478911,1.345191e-02,1.120468,0,1,3,2
6,11.627438,0.171947,6.542669,9.646653,14.094723,7.517125,0.148843,8.703550,11.302795,11.523045,...,2.230754,1.990131,13.777666,4.949609,2.267384e-03,1.990847,0,1,2,1
8,NaN,NaN,1.050328,6.320087,10.991098,6.414567,NaN,6.083151,NaN,10.138920,...,NaN,NaN,14.097099,NaN,NaN,NaN,0,1,1,0
9,8.856791,0.359993,1.050328,6.216077,11.916255,7.351426,0.218458,7.496613,15.497964,7.903915,...,1.763765,2.442616,15.750502,8.851677,4.986116e-02,1.536222,0,1,1,0
12,9.946200,0.066251,2.341356,7.711174,12.148604,6.661479,0.180765,3.964911,13.967877,14.787641,...,2.254819,5.180922,9.010082,12.168719,8.375832e-02,2.266575,0,2,2,0
21,NaN,NaN,1.838074,6.424482,12.793945,7.806704,NaN,11.077506,NaN,3.034513,...,NaN,NaN,18.705610,NaN,NaN,NaN,0,2,2,0
22,5.265636,0.015869,4.463894,8.715047,12.603403,6.034953,0.058906,6.952621,12.754314,12.199552,...,1.194403,1.151316,12.536835,3.419186,1.865950e-02,1.105283,0,0,0,0
23,9.538384,0.412610,2.363238,7.417853,13.790046,8.312447,0.509588,6.498729,14.658608,10.803126,...,2.240590,3.837530,13.434123,10.719493,8.943653e-03,1.928009,0,3,3,0
24,NaN,NaN,1.312910,6.527708,12.670870,7.824360,NaN,3.004667,NaN,15.270965,...,NaN,NaN,9.140132,NaN,NaN,NaN,0,1,1,0
27,NaN,NaN,1.028446,5.987763,10.655475,5.959166,NaN,5.125236,NaN,11.631574,...,NaN,NaN,13.261054,NaN,NaN,NaN,0,1,1,0
28,NaN,NaN,1.312911,6.886729,12.306725,7.457431,NaN,6.796169,NaN,9.275740,...,NaN,NaN,14.359195,NaN,NaN,NaN,0,1,1,0
30,8.137188,0.211851,1.816193,6.215176,11.185820,5.830767,0.059349,5.090793,12.587746,12.478836,...,1.569807,1.069079,12.954856,2.769691,5.459061e-07,1.388117,0,0,4,4
31,8.554136,0.041446,1.291029,6.837924,12.603404,7.728948,0.123929,4.603706,10.779298,12.720497,...,3.049463,5.427632,11.469686,7.711833,5.973979e-03,2.400050,0,1,1,0
32,NaN,NaN,1.312910,6.428450,11.685932,6.920709,NaN,2.156773,NaN,16.611678,...,NaN,NaN,7.508456,NaN,NaN,NaN,0,1,1,0
33,6.288177,0.407525,1.312909,6.529820,12.688605,7.771166,0.287112,2.038716,16.810813,16.798351,...,1.017347,0.729265,7.017046,4.817017,2.474223e-01,0.796533,0,1,1,0
34,NaN,NaN,1.553611,6.779448,12.321500,6.976744,NaN,6.537548,NaN,9.926923,...,NaN,NaN,14.164228,NaN,NaN,NaN,0,0,2,2
35,NaN,NaN,1.794310,6.942488,12.292375,6.839776,NaN,8.565451,NaN,6.962594,...,NaN,NaN,16.185658,NaN,NaN,NaN,0,0,1,1
36,NaN,NaN,3.916848,8.500203,14.775678,8.743364,NaN,7.804670,NaN,10.301715,...,NaN,NaN,13.894053,NaN,NaN,NaN,0,0,1,1
37,9.045057,0.085665,3.916848,6.496552,15.613993,9.615516,0.135625,7.400170,13.158834,10.941320,...,2.059047,2.664474,15.400550,5.233297,1.847926e-02,1.959776,0,0,1,1
39,10.719571,0.080812,5.229758,9.233140,14.376724,8.071645,0.140160,9.149136,12.587746,9.497141,...,2.144040,1.874999,14.724620,6.763717,4.919843e-03,1.964652,0,0,1,1
40,9.032563,2.767934,1.312910,6.961174,13.007360,8.159474,3.111062,6.432395,14.972248,9.850952,...,1.890969,3.597131,13.846988,9.873271,7.107372e-01,1.798435,0,2,2,0
42,5.340648,3.233160,3.916850,8.471164,14.231437,8.150425,2.133647,9.177408,16.817891,8.131105,...,1.084101,0.562831,15.469439,3.907324,3.065766e+00,0.626694,0,0,2,2
43,7.946330,7.827175,1.028447,6.351535,9.885333,5.273912,7.584039,8.081658,15.361419,6.956805,...,1.647542,2.975103,16.213114,8.302495,2.690857e+00,1.509052,0,1,1,0
46,NaN,NaN,2.253830,6.486413,12.028101,6.553963,NaN,6.568655,NaN,10.582448,...,NaN,NaN,14.497420,NaN,NaN,NaN,0,3,3,0
51,NaN,NaN,1.838074,6.750241,11.556894,6.449896,NaN,5.813511,NaN,11.358078,...,NaN,NaN,13.296742,NaN,NaN,NaN,0,1,1,0
52,5.998656,0.058548,1.028447,6.366319,12.061445,7.367406,0.105914,7.206766,12.468768,8.340206,...,1.607530,1.628289,15.315695,4.143336,7.351065e-03,1.306053,0,2,2,0
54,5.726834,0.749568,1.291029,6.580803,11.756788,6.819882,0.545566,4.682411,16.578186,12.596049,...,0.895969,1.048483,11.929410,4.664692,8.594683e-02,0.785667,0,1,1,0
55,8.520510,0.035822,0.787746,6.323127,10.478943,6.206807,0.130472,7.243918,10.814991,8.039216,...,2.519924,5.312500,15.394307,7.637178,6.640126e-03,2.373578,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228655,NaN,NaN,1.838075,6.486784,11.805637,6.742278,NaN,6.882417,NaN,9.667897,...,NaN,NaN,14.851276,NaN,NaN,NaN,0,2,2,0
228657,9.619069,0.328563,1.291029,6.703293,11.503289,6.575965,0.524793,4.665022,14.546748,12.623544,...,2.176128,4.058018,11.743630,10.974392,9.536287e-02,1.985969,0,1,1,0
228658,9.193006,0.055774,1.291028,6.204360,11.636386,6.775435,0.145718,5.777855,10.041643,10.863902,...,3.696371,7.845394,13.848672,9.122806,1.466965e-01,2.950252,0,1,1,0
228659,NaN,NaN,2.494530,6.632032,10.717937,5.100392,NaN,5.357811,NaN,12.739309,...,NaN,NaN,12.827433,NaN,NaN,NaN,0,3,3,0
228660,9.575062,1.300537,5.492341,8.650387,12.097035,3.793575,2.335487,5.164645,14.260896,16.061790,...,2.484684,4.846390,9.753197,11.405676,1.309991e+00,2.140204,0,1,3,2
228663,NaN,NaN,2.341356,7.095559,12.263179,6.963882,NaN,6.577233,NaN,10.656972,...,NaN,NaN,13.881749,NaN,NaN,NaN,0,1,1,0
228666,8.055434,0.171407,1.291029,6.335824,10.627713,5.724144,0.124306,3.928776,16.112186,13.787715,...,1.412426,1.639037,11.088264,7.300602,4.670769e-02,1.246700,0,1,1,0
228668,14.882313,0.157079,1.291028,6.394430,10.115593,5.317180,0.150321,5.913757,10.148721,10.649012,...,2.770511,3.223685,13.813233,9.406495,9.564098e-03,2.785707,0,2,2,0
228670,7.202643,2.424658,3.785558,7.042146,11.399402,5.601469,2.153922,7.169265,16.492224,11.174300,...,1.308619,1.194306,14.633224,6.065402,3.054839e+00,1.026424,0,2,2,0
228671,8.605211,1.142149,0.853392,6.385065,11.756788,7.343070,1.170488,4.604742,15.565307,12.278417,...,1.592154,2.437127,12.065485,8.574150,6.571835e-01,1.495398,0,1,1,0
228673,NaN,NaN,1.269147,6.315532,10.787303,6.090737,NaN,5.708103,NaN,10.952175,...,NaN,NaN,13.642708,NaN,NaN,NaN,0,1,1,0
228677,8.836584,0.195443,3.916848,7.734646,14.202355,8.174601,0.145123,6.912846,12.992266,11.711888,...,2.540647,2.598684,13.611124,5.711087,1.805020e-02,2.049363,0,0,1,1
228680,NaN,NaN,5.229760,8.953315,12.168990,4.156057,NaN,4.984705,NaN,16.082048,...,NaN,NaN,8.895914,NaN,NaN,NaN,0,0,2,2
228682,NaN,NaN,1.312910,6.863498,12.867557,8.047992,NaN,5.234451,NaN,11.745171,...,NaN,NaN,12.376555,NaN,NaN,NaN,0,1,1,0
228683,8.928965,1.756440,5.229759,8.725759,14.731332,8.496279,1.882675,7.583298,14.946568,11.973085,...,1.877694,3.635122,13.371271,9.830059,2.027626e-01,1.790912,0,0,1,1
228684,11.291191,0.215781,1.291027,6.258741,11.130488,6.358391,0.166806,7.635171,10.148721,7.927068,...,2.133632,1.463817,15.852846,3.837253,7.758699e-03,1.805540,0,1,1,0
228688,NaN,NaN,1.291029,6.733386,10.478943,5.585285,NaN,8.674333,NaN,6.283916,...,NaN,NaN,16.462897,NaN,NaN,NaN,0,1,1,0
228691,NaN,NaN,2.297593,7.347997,13.003046,7.588482,NaN,5.169319,NaN,12.839158,...,NaN,NaN,11.660629,NaN,NaN,NaN,0,1,1,0
228695,NaN,NaN,0.787747,6.130419,10.157006,5.902220,NaN,8.545732,NaN,5.980754,...,NaN,NaN,16.827387,NaN,NaN,NaN,0,2,2,0
228697,NaN,NaN,1.312910,6.225710,11.032517,6.165264,NaN,5.657713,NaN,11.075898,...,NaN,NaN,13.677048,NaN,NaN,NaN,0,1,1,0
228699,NaN,NaN,1.050329,6.128435,10.991098,6.442103,NaN,9.032249,NaN,5.475726,...,NaN,NaN,17.261226,NaN,NaN,NaN,0,1,1,0
228701,8.539653,3.199958,1.816192,6.274308,13.105814,7.728289,4.587994,8.504794,15.319092,7.080529,...,2.081394,2.992509,16.675772,8.938288,3.258223e+00,1.601009,0,0,1,1
228702,8.648951,2.208724,2.625820,6.926968,12.181852,6.586016,2.011566,6.937660,14.893389,10.373345,...,1.477842,3.563568,14.482683,9.584635,5.664891e-01,1.738246,0,1,1,0
228705,7.770079,0.932377,1.291029,6.858516,12.061446,7.274031,0.978175,5.803023,15.778856,10.824109,...,1.833479,2.513191,13.160439,7.654333,5.673148e-01,1.383798,0,1,1,0
228707,NaN,NaN,1.312909,6.581034,12.148605,7.302885,NaN,8.172110,NaN,7.100065,...,NaN,NaN,16.107744,NaN,NaN,NaN,0,2,2,0
228708,NaN,NaN,1.444201,6.368061,11.865255,7.088172,NaN,7.281489,NaN,8.640475,...,NaN,NaN,15.392866,NaN,NaN,NaN,0,1,1,0
228710,NaN,NaN,6.236324,9.443324,14.924483,8.455263,NaN,6.721720,NaN,14.348455,...,NaN,NaN,11.248736,NaN,NaN,NaN,0,1,2,1
228711,10.069277,0.323324,2.078775,6.698925,12.269012,6.570625,0.296536,3.029508,13.688847,16.002461,...,2.458328,5.834772,8.893134,12.743060,1.567642e-01,2.417606,0,1,3,2
228712,10.106144,0.309226,1.291029,6.692204,12.573678,7.730751,0.471351,5.089198,12.115532,11.952825,...,3.311224,11.175868,12.381113,15.357450,4.906576e-01,3.526650,0,1,1,0
228713,8.473141,3.479754,0.853391,6.306396,11.967826,7.496000,2.372586,6.533439,15.217671,9.228710,...,1.397909,3.051251,14.635298,8.969215,3.135205e+00,1.604493,0,1,1,0

In [8]:
# fill NaN by 0
features.fillna(value=0,inplace=True)

In [9]:
# features
x=np.array(features)

# Gradient boosting

In [10]:
# cross-validation
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import cross_validation
from sklearn.cross_validation import KFold
import time
import datetime
start_time = datetime.datetime.now()
kf=KFold(length,n_folds=5,shuffle=True)
n=[10]
t=[0]
for i,v in enumerate(n):
    start_time = datetime.datetime.now()
    clf = GradientBoostingClassifier(n_estimators=v,verbose=True,random_state=241,learning_rate=0.3)
    sc=cross_validation.cross_val_score(clf,x,y,scoring='roc_auc',cv=kf)
    t[i]=sc.mean()
    print 'Time elapsed:', datetime.datetime.now() - start_time

      Iter       Train Loss   Remaining Time
         1           1.0534            8.05s
         2           1.0304            5.79s
         3           1.0164            4.82s
         4           1.0075            3.91s
         5           1.0014            3.11s
         6           0.9973            2.43s
         7           0.9944            1.80s
         8           0.9921            1.17s
         9           0.9902            0.58s
        10           0.9885            0.00s
      Iter       Train Loss   Remaining Time
         1           1.0558            7.60s
         2           1.0331            5.46s
         3           1.0197            4.46s
         4           1.0107            3.65s
         5           1.0046            2.93s
         6           1.0000            2.29s
         7           0.9969            1.69s
         8           0.9945            1.12s
         9           0.9926            0.56s
        10           0.9909            0.00s
      Iter       Train Loss   Remaining Time
         1           1.0552            7.91s
         2           1.0322            5.77s
         3           1.0184            4.55s
         4           1.0093            3.75s
         5           1.0030            3.04s
         6           0.9986            2.38s
         7           0.9957            1.74s
         8           0.9933            1.14s
         9           0.9916            0.56s
        10           0.9898            0.00s
      Iter       Train Loss   Remaining Time
         1           1.0566            7.50s
         2           1.0335            5.57s
         3           1.0195            4.54s
         4           1.0111            3.72s
         5           1.0039            2.99s
         6           0.9998            2.34s
         7           0.9969            1.74s
         8           0.9944            1.15s
         9           0.9924            0.57s
        10           0.9907            0.00s
      Iter       Train Loss   Remaining Time
         1           1.0549            7.42s
         2           1.0318            5.43s
         3           1.0183            4.44s
         4           1.0100            3.68s
         5           1.0039            2.98s
         6           0.9999            2.33s
         7           0.9967            1.71s
         8           0.9941            1.14s
         9           0.9923            0.59s
        10           0.9908            0.00s
Time elapsed: 0:00:28.913478

In [11]:
t

[0.71150787742828747]

# Logistic Regression

In [ ]:
# standartization
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x=st.fit_transform(x)

In [ ]:
# cross_validation for logistic regresion
from sklearn.linear_model import LogisticRegression
n=[0.001,0.01,0.1,1,10,100,1000,10000]
t=[0,0,0,0,0,0,0,0]
for i, reg in enumerate(n):
    start_time = datetime.datetime.now()
    clf = LogisticRegression(penalty='l2',C=reg,random_state=241)
    sc=cross_validation.cross_val_score(clf,x,y,scoring='roc_auc',cv=kf)
    t[i]=sc.mean()
    print 'Time elapsed:', datetime.datetime.now() - start_time

In [ ]:
t

In [ ]:
# remove features
#features1=features.drop(['lobby_type','r1_hero','r2_hero','r3_hero','r4_hero','r5_hero','d1_hero','d2_hero','d3_hero','d4_hero','d5_hero'],axis=1)

In [ ]:
# new feature's matrix
x1=np.array(features1)
x1=st.fit_transform(x1)
len(x1[1])

In [ ]:
start_time = datetime.datetime.now()
for i in n:
    lr = LogisticRegression(penalty='l2',C=i, random_state=241)
    sc=cross_validation.cross_val_score(lr,x1,y,scoring='roc_auc',cv=kf)
    print sc.mean()

In [ ]:
features_players=np.array(features[['r1_hero','r2_hero','r3_hero','r4_hero','r5_hero','d1_hero','d2_hero','d3_hero','d4_hero','d5_hero']])
players=np.unique(features_players)
players

In [ ]:
len(players)

In [ ]:
X_pick = np.zeros((features.shape[0], 112))

for i, match_id in enumerate(features.index):
    for p in xrange(5):
        X_pick[i, features.ix[match_id, 'r%d_hero' % (p+1)]-1] = 1
        X_pick[i, features.ix[match_id, 'd%d_hero' % (p+1)]-1] = -1

In [ ]:
sum(X_pick)

In [ ]:
# delete extra players
X_pick=X_pick[:,sum(X_pick)!=0]

In [ ]:
x2=np.hstack((x1,X_pick))
x2.shape

In [ ]:
# last logistic regression
for i in n:
    lr = LogisticRegression(penalty='l2',C=i, random_state=241)
    sc=cross_validation.cross_val_score(lr,x2,y,scoring='roc_auc',cv=kf)
    print sc.mean()

In [ ]:
n

# Построение прогноза (логистическая регрессия)

In [17]:
#lr_final = LogisticRegression(penalty='l2',C=0.1, random_state=241)
clf_final = GradientBoostingClassifier(n_estimators=40,verbose=True,random_state=241,learning_rate=0.3)

In [14]:
features_test = pandas.read_csv('test_bnp.csv',index_col='ID')
features_test1=features_test[float_feat.index]
features_test1.head()

,v5,v8,v10,v12,v14,v21,v25,v34,v36,v40,...,v108,v109,v114,v117,v124,v128,v38,v62,v72,v129
ID,,,,,,,,,,,,,,,,,,,,,
0,6.57700,0.011094,1.312911,6.961173,12.230137,7.437806,0.069180,5.228503,12.183225,11.754576,...,1.502480,2.121710,12.246698,4.777902,1.112270e-07,1.485925,0,1,1,0
1,NaN,NaN,1.291029,6.618289,10.760796,5.895192,NaN,8.387431,NaN,6.737574,...,NaN,NaN,16.284938,NaN,NaN,NaN,4,1,5,0
2,6.55010,0.007164,1.575492,6.894249,13.306189,8.253452,0.059620,7.958990,12.195123,7.701325,...,1.188768,2.088817,15.622710,4.740574,1.412265e-02,1.475892,0,1,1,0
7,9.77308,1.252157,1.575493,6.856236,10.397026,5.539484,1.779993,6.223849,13.741929,10.444974,...,2.690866,6.211596,13.701587,12.446092,1.100329e+00,2.448814,0,1,1,0
10,8.52051,0.074263,1.050328,6.273627,11.354501,6.741530,0.158719,5.476858,10.814992,11.097606,...,2.467017,5.312500,13.395401,7.637177,2.584588e-01,2.374275,0,2,2,0

In [ ]:
features_test1=features_test.drop(['lobby_type','r1_hero','r2_hero','r3_hero','r4_hero','r5_hero','d1_hero','d2_hero','d3_hero','d4_hero','d5_hero'],axis=1)

In [15]:
features_test1.fillna(value=0,inplace=True)
x_test=np.array(features_test1)
#x_test=st.transform(x_test)

/Applications/anaconda/lib/python2.7/site-packages/pandas/core/frame.py:2650: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [ ]:
X_pick_test = np.zeros((features_test.shape[0], 112))

for i, match_id in enumerate(features_test.index):
    for p in xrange(5):
        X_pick_test[i, features_test.ix[match_id, 'r%d_hero' % (p+1)]-1] = 1
        X_pick_test[i, features_test.ix[match_id, 'd%d_hero' % (p+1)]-1] = -1

In [ ]:
X_pick_test1=X_pick_test[:,sum(X_pick_test)!=0]
X_pick_test1.shape

In [ ]:
X_pick_test2=X_pick_test[:,108:109]
X_pick_test2

In [ ]:
X_pick_test3=np.hstack((X_pick_test1[:,0:105],X_pick_test2))
X_pick_test4=np.hstack((X_pick_test3,X_pick_test1[:,105:107]))

In [ ]:
x3=np.hstack((x_test,X_pick_test4))
x3.shape

In [18]:
clf_final.fit(x,y)

      Iter       Train Loss   Remaining Time
         1           1.0552           36.74s
         2           1.0325           28.92s
         3           1.0188           25.79s
         4           1.0098           23.98s
         5           1.0038           22.61s
         6           0.9997           21.14s
         7           0.9965           20.19s
         8           0.9946           18.70s
         9           0.9924           17.76s
        10           0.9911           17.03s
        20           0.9798           10.56s
        30           0.9753            4.96s
        40           0.9719            0.00s

GradientBoostingClassifier(init=None, learning_rate=0.3, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=40,
              random_state=241, subsample=1.0, verbose=True,
              warm_start=False)

In [19]:
pred = clf_final.predict_proba(x_test)[:, 1]

In [20]:
min(pred)

0.0038740057490163401

In [21]:
max(pred)

0.98526780271200842

In [22]:
pred

array([ 0.32140679,  0.91637433,  0.72707632, ...,  0.80078458,
        0.66309536,  0.51983591])

In [23]:
imp=pandas.DataFrame(pred,index=features_test.index)

In [24]:
imp

               0
ID
0       0.321407
1       0.916374
2       0.727076
7       0.689921
10      0.758378
11      0.562784
13      0.901953
14      0.610605
15      0.853157
16      0.854146
17      0.657576
18      0.851751
19      0.839530
20      0.824662
25      0.825916
26      0.857401
29      0.716641
38      0.939907
41      0.815341
44      0.666115
45      0.564173
47      0.828887
48      0.852532
49      0.759234
50      0.911701
53      0.540550
56      0.430021
59      0.850937
60      0.515542
64      0.789034
...          ...
228650  0.696682
228656  0.822670
228661  0.415457
228662  0.762370
228664  0.791835
228665  0.886043
228667  0.663599
228669  0.906397
228672  0.798299
228674  0.486639
228675  0.683530
228676  0.854068
228678  0.702517
228679  0.788514
228681  0.954972
228685  0.798258
228686  0.909954
228687  0.721842
228689  0.829844
228690  0.948980
228692  0.726028
228693  0.717543
228694  0.799087
228696  0.748011
228698  0.867397
228700  0.761212
228703  0.516290
228704  0.800785
228706  0.663095
228709  0.519836

[114393 rows x 1 columns]

In [25]:
pandas.DataFrame.to_csv(imp,'bnp_kaggle')